#! /bin/env python 
'''
Created on Oct 28, 2012

@author: Shunping Huang
'''

import os
import pysam
import argparse as ap 
from modtools.mod2 import Mod
from modtools.utils import *
from modtools import tmpmod
from modtools import alias

from time import localtime,strftime

DESC = 'A FASTA generator for in silico genomes'

#modfile = "../../data/C.mod" 
#infasta = "../../data/ref.chr1_chr10.fa"
#chroms = ['1','10']
#outfasta = "out.fa"
#width = 72


def seq2fasta(fp, sample, seq, chrom, width):
    fp.write('>%s chromosome:%s:%s:1:%d:1 %s\n' 
             % (chrom, sample, chrom, len(seq), strftime("date:%Y%m%d",localtime())))
    length = len(seq)
    for i in range(0, length, width):
        if (i+width)<=length:
            fp.write(seq[i:i+width])
        else:
            fp.write(seq[i:])
        fp.write('\n')
    fp.flush()


if __name__ == '__main__':    
    ## Parse arguments
    p = ap.ArgumentParser(description=DESC, 
                          formatter_class = ap.RawTextHelpFormatter)
    group = p.add_mutually_exclusive_group()    
    group.add_argument("-q", dest='quiet', action='store_true',
                       help='quiet mode')
    group.add_argument('-v', dest='verbosity', action="store_const", const=2,
                       default=1, help='verbose mode')        
    p.add_argument('-c', metavar='chromList', dest='chroms', type=validChromList,
                   default = [],
                   help='a comma-separated list of chromosomes in output' +
                        ' (default: all)')
    p.add_argument('-s', metavar='sample', dest='sample', default=None, 
                   help='sample name (default: <mod_prefix>)')
    p.add_argument('-a', metavar='aliasFile', dest='alias', 
                   type=readableFile, default = None,
                   help='the file of chromosome name alias definition' +
                        ' (default: none)')
    p.add_argument('-w', metavar='width', dest='width', type=int, default = 72,  
                   help='the width in output FASTA  (default: 72)')    
    p.add_argument('-o', metavar='out.fa', dest='outfasta', type=writableFile, 
                   default=None, help='the output FASTA file ' + 
                   '(default: out.fasta)')
    
    p.add_argument('mod', metavar='in.mod', 
                   type=readableFile, help='an input MOD file')
                        
    p.add_argument('infasta', metavar='in.fa',
                   type=readableFile, help='an input (reference) FASTA file')                    
        
    args = p.parse_args()
    
    if args.quiet:
        VERBOSITY = 0
    else:            
        VERBOSITY = args.verbosity
        
    if args.sample is None:
        sample = os.path.basename(args.mod)
        idx = sample.index('.')
        if idx >= 0:
            sample = sample[:idx]
        sample.replace(':','_')
    else:
        sample = args.sample
    
    if args.outfasta is None:               
        outfasta = open('out.fa', 'wb')
    else:        
        outfasta = open(args.outfasta, 'wb')
        
    if args.alias is None:        
        chromAliases = alias.chromAliases
    else:
        chromAliases = alias.Alias()
        chromAliases.readFromFile(args.alias)
    
    chroms = args.chroms 
    width = args.width
    
    # A compromise: adding complexity but reducing unnecessary argument.
    if VERBOSITY > 0:
        log("extracting MOD file ...\n", 1, True)
    tmpmod = tmpmod.getTabixMod(args.mod)
    mod = Mod(tmpmod)
                
    if len(args.chroms) == 0: 
        chroms = mod.chroms
                    
    # Build index on fasta
    if not os.path.isfile(args.infasta+'.fai'):
        pysam.faidx(args.infasta)            
    
    fp = open(args.infasta+'.fai')
    inChromLengths = {}
    for line in fp:
        tmp = line.rstrip().split('\t')
        inChromLengths[tmp[0]] = int(tmp[1])
    fp.close()
     
#    print (inChromLengths)

    infasta = pysam.Fastafile(args.infasta)
        
    if VERBOSITY > 0:                            
        log("input MOD file: %s (%s)\n" % (args.mod, mod.fileName), 1, True)
        log("input FASTA file: %s\n" % infasta.filename, 1, True)
        log("output FASTA file: %s\n" % outfasta.name, 1, True)                
    
    for outChrom in chroms:
        if VERBOSITY > 0:
            log("processing chromosome '%s'\n" % outChrom, 1, True)         
        chrom = chromAliases.getBasicName(outChrom)
        
        modChrom = chromAliases.getMatchedAlias(chrom, mod.chroms)
        if modChrom is None:
            if VERBOSITY > 0:
                log("chromosome alias not found for '%s' in MOD\n" % outChrom, 1, True) 
            modChrom = chrom
        else:
            if VERBOSITY > 0:
                log("chromosome alias '%s' used for '%s' in MOD\n" % 
                    (modChrom, outChrom), 1, True)      
        mod.load(modChrom)
        
        if VERBOSITY > 0:
            log("%d line(s) found in MOD\n" % len(mod.data), 1, True)
            if len(mod.data) == 0:
                log("Warning: chromosome '%s' not found in MOD, " % outChrom + 
                    "maybe incorrect name or alias\n" 
                    , 2, True)
                    
#        posmap=mod.getPosMap(chrom, fastaChromLens[chrom])
#        print(posmap.toCSV()[:1000])
        
        inFastaChrom = chromAliases.getMatchedAlias(chrom, inChromLengths.keys())
        if inFastaChrom is None:
            if VERBOSITY > 0:
                log("chromosome alias not found for '%s' in FASTA\n" % 
                    outChrom, 1, True)
            inFastaChrom = chrom
        else:
            if VERBOSITY > 0:
                log("chromosome alias '%s' used for '%s' in FASTA\n" % 
                    (inFastaChrom, outChrom), 1, True)        
                      
        seq=mod.getSeq(infasta, modChrom, chromAliases, inChromLengths)
        if VERBOSITY > 0:
            log("old: %d bp -> new: %d bp\n" % (inChromLengths[inFastaChrom], len(seq)), 
                1, True)            
                        
        seq2fasta(outfasta, sample, seq, outChrom, width)
        
    outfasta.close()
    # Clean up the temp files
    os.remove(mod.fileName)
    os.remove(mod.fileName+'.tbi')
    
    if VERBOSITY > 0:
        log("All Done!\n", 1, True)